### ISSUE TITLE
Edlib docker install - unhealthy containers

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#1466]
**Containers with status (unhealthy)**
```
edlib_authapi_1                      docker-entrypoint.sh /bin/ ...   Up (unhealthy)                                                                                                                                           
edlib_common-subscribers_1           docker-entrypoint-dev.sh / ...   Up               9000/tcp                                                                                                                                
edlib_common_1                       /docker-entrypoint.sh ngin ...   Up (unhealthy)   80/tcp                                                                                                                                  
edlib_contentauthor-cron_1           /docker-entrypoint-dev.sh  ...   Up               9000/tcp                                                                                                                                
edlib_contentauthor-fpm_1            /docker-entrypoint-dev.sh  ...   Up (healthy)     9000/tcp                                                                                                                                
edlib_contentauthor-horizonqueue_1   /docker-entrypoint-dev.sh  ...   Up               9000/tcp                                                                                                                                
edlib_contentauthor-subscribers_1    /docker-entrypoint-dev.sh  ...   Up               9000/tcp                                                                                                                                
edlib_contentauthor_1                /docker-entrypoint.sh nginx      Up (healthy)     80/tcp                                                                                                                                  
edlib_dokuapi_1                      docker-entrypoint.sh /bin/ ...   Up (healthy)                                                                                                                                             
edlib_edlib-common-fpm_1             docker-entrypoint-dev.sh p ...   Up (healthy)     9000/tcp                                                                                                                                
edlib_edlibapi-url_1                 docker-entrypoint.sh /bin/ ...   Up (unhealthy)   80/tcp                                                                                                                                  
edlib_elasticsearch_1                /tini -- /usr/local/bin/do ...   Up (healthy)     0.0.0.0:9200->9200/tcp, 9300/tcp                                                                                                        
edlib_elasticsearch_password_1       generate-password password.txt   Exit 0                                                                                                                                                   
edlib_ltiapi-subscribers_1           docker-entrypoint.sh /bin/ ...   Up                                                                                                                                                       
edlib_ltiapi_1                       docker-entrypoint.sh /bin/ ...   Up (healthy)                                                                                                                                             
edlib_mysql_1                        docker-entrypoint.sh --ini ...   Up (healthy)     0.0.0.0:3306->3306/tcp                                                                                                                  
edlib_nginx_1                        /docker-entrypoint.sh ngin ...   Up (healthy)     0.0.0.0:443->443/tcp, 0.0.0.0:80->80/tcp                                                                                                
edlib_npm-components-storybook_1     docker-entrypoint.sh /bin/ ...   Up (healthy)     9009/tcp                                                                                                                                
edlib_postgres_1                     docker-entrypoint.sh postgres    Up (healthy)     0.0.0.0:5432->5432/tcp                                                                                                                  
edlib_proxy-admin_1                  docker-entrypoint.sh /bin/ ...   Up (unhealthy)   3000/tcp, 3001/tcp                                                                                                                      
edlib_proxy-auth_1                   docker-entrypoint.sh /bin/ ...   Up (healthy)     80/tcp                                                                                                                                  
edlib_proxy-lti_1                    docker-entrypoint.sh /bin/ ...   Up (healthy)     80/tcp                                                                                                                                  
edlib_proxy-resource_1               docker-entrypoint.sh /bin/ ...   Up (unhealthy)   80/tcp                                                                                                                                  
edlib_rabbitmq_1                     docker-entrypoint.sh rabbi ...   Up (healthy)     15671/tcp, 0.0.0.0:15672->15672/tcp, 15691/tcp, 15692/tcp, 25672/tcp, 4369/tcp, 5671/tcp, 0.0.0.0:5672->5672/tcp, 0.0.0.0:5673->5673/tcp
edlib_redis_1                        docker-entrypoint.sh redis ...   Up (healthy)     0.0.0.0:6379->6379/tcp                                                                                                                  
edlib_resourceapi-subscribers_1      docker-entrypoint.sh /bin/ ...   Up                                                                                                                                                       
edlib_resourceapi_1                  docker-entrypoint.sh /bin/ ...   Up (healthy)                                                                                                                                             
edlib_urlapi_1                       docker-entrypoint.sh /bin/ ...   Up (unhealthy)                                                                                                                                           
edlib_versionapi_1                   /usr/local/bin/mvn-entrypo ...   Up (healthy)     0.0.0.0:5504->5504/tcp                                                                                                                  
edlib_www_1                          docker-entrypoint.sh /bin/ ...   Up (unhealthy)   3000/tcp
```

**To Reproduce**
Run the setup guide until step 3 https://docs.edlib.com/docs/developers/getting-started and the `docker-compose ps` command to get a health check on all containers.

**Screenshots**
![Skjermbilde 2022-08-02 kl  14 28 37](https://user-images.githubusercontent.com/38659798/182376912-a26c7ca5-acaf-4c67-a63d-bb673b4a0cea.png)

**Desktop (please complete the following information):**

- OS: MacOS (Intel based)

**Unhealty containers**
- [x] [edlib_authapi_1](https://github.com/cerpus/Edlib/issues/1467)
- [x] [edlib_common_1](https://github.com/cerpus/Edlib/issues/1468)
- [x] [edlib_edlibapi-url_1](https://github.com/cerpus/Edlib/issues/1469)
- [x] [edlib_proxy-admin_1](https://github.com/cerpus/Edlib/issues/1470)
- [x] [edlib_proxy-resource_1](https://github.com/cerpus/Edlib/issues/1471)
- [x] [edlib_urlapi_1](https://github.com/cerpus/Edlib/issues/1472)
- [ ] [edlib_www_1](https://github.com/cerpus/Edlib/issues/1473)
