### ISSUE TITLE
New design

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#2509]
- [x] 1. Filter desktop: https://github.com/cerpus/Edlib/pull/2496
- [x] 2. Search/filter mobile: https://github.com/cerpus/Edlib/pull/2513
- [x] 3. [Search/filter desktop](https://github.com/cerpus/Edlib/issues/2516)  https://github.com/cerpus/Edlib/pull/2518
- [x] 4. [Results page (list) desktop](https://github.com/cerpus/Edlib/issues/2510)
- [x] 5. Results page (card) desktop/mobile: https://github.com/cerpus/Edlib/pull/2499
- [x] 6. [Preview modal/page](https://github.com/cerpus/Edlib/issues/2512)
- [x] 7. [F4M view](https://github.com/cerpus/Edlib/issues/2511)
- [ ] 8. [Email template](https://github.com/cerpus/Edlib/issues/2520)
- [ ] 9. [Detail view](https://github.com/cerpus/Edlib/issues/2577)
